#pragma once
#include <string>
#include <iostream>
#include "BaseWord.h"
#include "RelationalOperator.h"
#include "LogicalOperator.h"
#include "ArithmeticOperator.h"
#include "Keyword.h"
#include "Identifier.h"